### ISSUE TITLE
Rename to /usr/bin/bootterm?

### ISSUE THREAD

**Issue by paravoid** [wtarreau/bootterm#17]
I find `/usr/bin/bt` to be a bit... generic? If I installed it a while back, and looked in my /usr/bin, I'd probably wouldn't remember what it. Conversely, if I wanted to connect to my new ESP32 board after not having done so in a while, I'd probably remember this "bootterm" utility, and I'd probably try to type "bootterm", rather than "bt".

(And this may be me, but when I see "bt", I can't stop but think "Bluetooth" for a second.)

With a quick search, I couldn't find of another package shipping in `{/bin,/sbin,/usr/bin,/usr/sbin}/bt`, but it seems a bit risky, in the context of a larger namespace, like ones that distributions maintain. (I'm looking into packaging BootTerm for/in Debian, which enforces uniqueness in $PATH; no other package will be able to use "bt" if BootTerm does.)

Any reason to not use `/usr/bin/bootterm` instead? Users can always add `alias bt=booterm` in their preferred shell if they use this often and want to save a few characters.

**Comment by wtarreau** [comment]
I'm figuring that we covered this point during our private conversations, closing now :-)
